### PR TITLE
Replace hardcoded codec

### PR DESCRIPTION
**Pull request by qcho**
codecRegistryWithNullSerialization was hardCoded. Trying to fix Litote/kmongo#115

### CODE REVIEW

**Comment by qcho** [comment]
I've fixed the issue. Sending a pull request now.

It was a mix of two things.
**First**: `PojoClassMappingTypeService` was wrong due to https://github.com/Litote/kmongo/issues/115#issuecomment-465244058
**Second**: I was wrong on the usage of `save()` because it doesn't perform `updateOne`, instead it does a `replaceOne` following mongodb's spec.

So doing `col.updateOne(<DOCUMENT>, upsert())` instead of `col.save(<DOCUMENT>)` plus **First** fixed does the trick.

```kotlin
import org.bson.codecs.pojo.annotations.BsonId
import org.litote.kmongo.* //NEEDED! import KMongo extensions
import org.litote.kmongo.util.ObjectMappingConfiguration
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {

    data class Document(
            @BsonId val id: Int,
            val field1: String,
            val field2: String?
    )

    @Test fun testMongoBehaviours() {
        val client = KMongo.createClient() //use coroutine extension
        val database = client.getDatabase("test") //normal java driver usage
        val col = database.getCollection<Document>() //KMongo extension method
        ObjectMappingConfiguration.serializeNull = false
        col.deleteMany()
        run {
            col.updateOne(Document(1, "Hello1", null), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello1", document.field1)
            assertEquals(null, document.field2)
        }
        run {
            col.updateOne(Document(1, "Hello2", "World2"), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello2", document.field1)
            assertEquals("World2", document.field2)
        }
        run {
            col.updateOne(Document(1, "Hello3", null), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello3", document.field1)
            assertEquals("World2", document.field2) // because it was null
        }
    }
}
```

**Comment by zigzago** [comment]
Using codecRegistryWithNullSerialization was intentional. But your are right, there is a lack of documentation. 

With your PR, a few tests are failing. For example, look at the test `canPartiallyUpdateWithANewDocument` in https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/UpdateTest.kt#L92 . Now `r.address` is not null. I expect it to be null, because when I update with an object, I expect that all fields are taken into account.

But your are right,  there should be an easier way to do "real" partial update - ie null fields ignored. The current way is to create an other class with only the fields you want to update.

1) We can easily add an updateNotNull method, in order to update only not null properties
2) May be it is more consistent for the current update method to _remove_ the null fields in Mongo (instead of setting them to null) when ObjectMappingConfiguration.serializeNull = false

What do you think?

**Comment by qcho** [comment]
The logical expectation from me is that it should work the same as the [POJO-mongo documentation explains](http://mongodb.github.io/mongo-java-driver/3.7/bson/pojos/#changing-what-is-serialized). **By default null values aren’t serialized.**

I don't share this expectation: 
> Now `r.address` is not null. I expect it to be null, because when I update with an object, I expect that all fields are taken into account.

This is what I expect:
The result should be product of the `ObjectMappingConfiguration.serializeNull` configuration. I'm not against to change the default to`ObjectMappingConfiguration.serializeNull = true` to allow backwards compatibility and to be consistent with Jackson by default.

Also using the `ObjectMappingConfiguration` seems better because adding one `updateNotNull` won't fix all of the `update***` methods that the API has.

**Comment by qcho** [comment]
I expect the "replace" methods to be used when needing to _remove_ fields from the db

**Comment by qcho** [comment]
A middle ground could be to have a nullValueStrategy option on every `update***` method to allow it to be `IGNORE` when you want to not serialize these fields or `UNSET` if you want the field to be removed from the db's document.
Maybe Annotating the data class too something like

```
    data class Document(
            @BsonId val id: Int,
            val field1: String,
            @IgnoreIfNull val field2: String?,
            @UsetIfNull val field3: String?,
    )
```

I know other language libraries like `C#` do have these options

**Comment by qcho** [comment]
On my end this is working:

```
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package indeed.historian

import org.bson.codecs.pojo.annotations.BsonId
import org.litote.kmongo.* //NEEDED! import KMongo extensions
import org.litote.kmongo.util.ObjectMappingConfiguration
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class AppTest {

    data class Document(
            @BsonId val id: Int,
            val field1: String,
            val field2: String?
    )

    @Test fun testMongoBehaviours() {
        val client = KMongo.createClient() //use coroutine extension
        val database = client.getDatabase("test") //normal java driver usage
        val col = database.getCollection<Document>() //KMongo extension method
        col.deleteMany()
        run {
            col.updateOne(Document(1, "Hello1", null), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello1", document.field1)
            assertNull(document.field2)
        }
        run {
            col.updateOne(Document(1, "Hello2", "World2"), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello2", document.field1)
            assertEquals("World2", document.field2)
        }
        val serializeNullDefault = ObjectMappingConfiguration.serializeNull
        run {
            ObjectMappingConfiguration.serializeNull = false
            col.updateOne(Document(1, "Hello3", null), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello3", document.field1)
            assertEquals("World2", document.field2) // because it was null
            ObjectMappingConfiguration.serializeNull = serializeNullDefault
        }
        run {
            ObjectMappingConfiguration.serializeNull = true
            col.updateOne(Document(1, "Hello3", null), upsert())
            val document = col.findOne(Document::id eq 1)
            assertNotNull(document)
            assertEquals("Hello3", document.field1)
            assertNull(document.field2) // because it was null && serializeNull=true
            ObjectMappingConfiguration.serializeNull = serializeNullDefault
        }
    }
}
```

**Comment by zigzago** [comment]
I think we have two options:

1) Add three methods
- `updateOneWithNotNull(filter: String, update: Any, options: UpdateOptions = UpdateOptions())`
- `updateOneWithNotNull(target: T, options: UpdateOptions = UpdateOptions())`
- `updateOneWithNotNullById(id: Any, update: Any, options: UpdateOptions = UpdateOptions())`

2) Add a parameter to the three current methods
- `updateOne(filter: String, update: Any, options: UpdateOptions = UpdateOptions(), updateOnlyNotNull:Boolean = UpdateConfiguration.updateOnlyNotNull)`
- `updateOne(target: T, options: UpdateOptions = UpdateOptions(), 
updateOnlyNotNull:Boolean = UpdateConfiguration.updateOnlyNotNull)`
- `updateOneById(id: Any, update: Any, options: UpdateOptions = UpdateOptions(), updateOnlyNotNull:Boolean = UpdateConfiguration.updateOnlyNotNull )`

when `UpdateConfiguration.updateOnlyNotNull :Boolean  = false`

I tend to prefer 2) as it keeps backward compatibility and allows to customize default behaviour

I plan to implement it tomorrow.

**Comment by qcho** [comment]
Sounds good to me. Glad I could help!

**Comment by zigzago** [comment]
Resolved by #115

**Pull request closed without merging**
